/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function DisketaMare({ position = [0, 0, 0], scale = [1, 1, 1], rotation = [0, 0, 0] }) {
  const { nodes, materials } = useGLTF('/3DObjects/Disketa-mare.glb')
  if (materials['Material.001']) {
    materials['Material.001'].metalness = 0.3; // Lower reflectiveness (0 is non-metallic)
    materials['Material.001'].roughness = 0.7; // Increase roughness (1 is fully rough)
  }

  if (materials['Material.002']) {
    materials['Material.002'].metalness = 0.3; // Lower reflectiveness (0 is non-metallic)
    materials['Material.002'].roughness = 0.5; // Increase roughness (1 is fully rough)
  }
  return (
    <group position={position} scale={scale} rotation={rotation} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rama_interior.geometry}
        material={materials['Material.003']}
        position={[0, -3.572, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.987}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ceva_pe_dreapta.geometry}
        material={materials['Material.004']}
        position={[0, -3.623, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rama_groasa.geometry}
        material={materials['Material.002']}
        position={[0, -3.623, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.interior.geometry}
        material={materials['Material.001']}
        position={[0, -3.623, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.931, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/3DObjects/Disketa-mare.glb')

export default DisketaMare;
