/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function DisketaMock({ position = [0, 0, 0], scale = [1, 1, 1], rotation = [0, 0, 0] }) {
const { nodes, materials } = useGLTF('/3DObjects/Disketa-meniu.glb')
  return (
    <group position={position} scale={scale} rotation={rotation} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.spate.geometry}
        material={materials['Material.010']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rama_interior.geometry}
        material={materials['Material.011']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.colturi.geometry}
        material={materials['Material.013']}
        rotation={[Math.PI / 2, 0, 0]}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.rama_exterior.geometry}
        material={materials['Material.012']}
        rotation={[Math.PI / 2, 0, 0]}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.view.geometry}
        material={materials['Material.009']}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/3DObjects/Disketa-meniu.glb')

export default DisketaMock;
